version: '3.5'

networks:
   awx:

volumes:
   postgres_data: {}
   rabbitmq_data: {}
   memcached_data: {}

services:

   postgres:
      image: postgres:10.5-alpine
      container_name: awx_postgres
      environment:
         - POSTGRES_DB=awx
         - PGDATA=/var/lib/postgresql/data
         - POSTGRES_USER=admin
         - POSTGRES_PASSWORD=password
      ports:
         - 5432:5432
      networks:
         - awx
      volumes:
         - postgres_data:/var/lib/postgresql/data

   rabbitmq:
      image: rabbitmq:3-management
      container_name: awx_rabbitmq
      volumes:
         - rabbitmq_data:/var/lib/rabbitmq
      environment:
         - RABBITMQ_DEFAULT_USER=admin
         - RABBITMQ_DEFAULT_PASS=password
         - RABBITMQ_DEFAULT_VHOST=awx
      ports:
         - 5672:5672
         - 5671:5671
         - 15672:15672
      networks:
         - awx

   memcached:
      image: memcached:alpine
      container_name: awx_memcached
      volumes:
         - memcached_data:/var/log/memcache
      ports:
         - 11211:11211
      networks:
         - awx

   awx_web:
      image: geerlingguy/awx_web:latest
      hostname: awxweb
      user: root
      environment:
         - SECRET_KEY=b2289d76-4758-43d4-90e1-f627f1c6d905
         - DATABASE_USER=admin
         - DATABASE_PASSWORD=password
         - DATABASE_NAME=awx
         - DATABASE_PORT=5432
         - DATABASE_HOST=awx_postgres
         - RABBITMQ_USER=admin
         - RABBITMQ_PASSWORD=password
         - RABBITMQ_HOST=awx_rabbitmq
         - RABBITMQ_PORT=5672
         - RABBITMQ_VHOST=awx
         - MEMCACHED_HOST=awx_memcached
         - MEMCACHED_PORT=11211
      ports:
         - 8052:8052
      networks:
         - awx
      depends_on:
         - postgres
         - rabbitmq
         - memcached

   awx_task:
      image: geerlingguy/awx_task:latest
      hostname: awx
      user: root
      environment:
         - SECRET_KEY=b2289d76-4758-43d4-90e1-f627f1c6d905
         - DATABASE_USER=admin
         - DATABASE_PASSWORD=password
         - DATABASE_NAME=awx
         - DATABASE_PORT=5432
         - DATABASE_HOST=awx_postgres
         - RABBITMQ_USER=admin
         - RABBITMQ_PASSWORD=password
         - RABBITMQ_HOST=awx_rabbitmq
         - RABBITMQ_PORT=5672
         - RABBITMQ_VHOST=awx
         - MEMCACHED_HOST=awx_memcached
         - MEMCACHED_PORT=11211
      networks:
         - awx
      depends_on:
         - postgres
         - rabbitmq
         - memcached
         - awx_web
